apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^create_course$', views.create_course, name="create_course"),
    url(r'^(?P<id>\d+)/remove$', views.remove, name="remove"),
    url(r'^addusertocourse$', views.addusertocourse, name="users_courses"),
    url(r'^adduser$', views.adduser, name="adduser")
]

apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register_user$', views.register_user, name="register_user"),
    url(r'^success$', views.success, name="success"),
    url(r'^login_user$', views.login_user, name="login_user"),
    url(r'^logout$',views.logout, name="logout")
]

multiple_apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
    
    url(r'^', include('apps.logreg.urls', namespace="my_users")),
    url(r'^courses/', include('apps.courses.urls', namespace="my_courses")),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace="my_timedisplay")),
    url(r'^randomword/', include('apps.randomword.urls', namespace="my_randomword")),
    url(r'^survey/', include('apps.survey.urls', namespace="my_survey")),
]

apps/logreg/models.py
from __future__ import unicode_literals

from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
import bcrypt

class UserManager(models.Manager):
	def register_user(self, data):
		password = data["password"].encode()
		hashed = bcrypt.hashpw(password, bcrypt.gensalt())
		
		errors = []
		if not data["first_name"]:
			errors.append("Please enter your first name")
		elif len(data["first_name"]) < 3:
			errors.append("Please enter more that 2 characters")
		if not data["last_name"]:
			errors.append("Please enter your last name")
		elif len(data["last_name"]) < 3:
			errors.append("Please enter more that 2 characters")
		if not data["email"]:
			errors.append("Please enter your email")
		elif not EMAIL_REGEX.match(data["email"]):
			errors.append("Invalid email")
		if not data["password"]:
			errors.append("Enter Password")
		elif not len(data["password"]) >= 8:
			errors.append("Need more characters!")
		if not data["confirm_password"]:
			errors.append("Confirm Password")
		elif data["confirm_password"] != data["password"]:
			errors.append("Passwords do not match")

		response = {}
		if not errors:
			new_user=self.create(first_name=data["first_name"],last_name=data["last_name"], email=data["email"], password=hashed, confirm_password=data["confirm_password"])
			response ["added"]=True
			response ["new_user"]= new_user
		else:
			response["added"]=False
			response["errors"]=errors
		return response

	def Login_user(self, data):
		user= self.filter(email=data["email"])
		print user
		errors=[]
		reqs={}
		if not user:
			errors.append("Please register or check spelling")
		else: 
			user=user[0]
			if bcrypt.hashpw(data['password'].encode(), user.password.encode()) ==user.password.encode():
				reqs["checked"]=True
				reqs["logger"]=user
			else: 
				errors.append("Email and Password do not match")
		
		if errors:
			reqs["checked"]=False
			reqs["errors"]=errors
		return reqs		


class User(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	confirm_password = models.CharField(max_length=255, default = 'SOME STRING')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()




# Create your models here.

apps/logreg/views.py
from django.shortcuts import render, redirect
from .models import User, UserManager
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
	
	return render(request, 'logreg/index.html')

def register_user(request):
	res = User.objects.register_user(request.POST)
	if res["added"]:
		request.session['logged_in']=True
		messages.success(request, "Successful Registration! Welcome, {}".format(res["new_user"].first_name))
		return redirect(reverse('my_users:success'))
	else:
		request.session['logged_in']=False
		for error in res["errors"]:
			messages.error(request, error)
		return redirect(reverse('my_users:index'))
def login_user(request):
	print("Something")
	reqs = User.objects.Login_user(request.POST)
	if reqs["checked"]:
		request.session['logged_in']=True
		messages.success(request, "Successful Login! Welcome, {}".format(reqs["logger"].first_name))
		return redirect(reverse('my_users:success'))
	else:
		for error in reqs["errors"]:
			request.session['logged_in']=False
			messages.error(request, error)
		return redirect(reverse('my_users:index'))

def success(request):
	if not request.session['logged_in']:
		return redirect(reverse('my_users:index'))
	return render(request,'logreg/success.html')

def logout(request):
	request.session['logged_in']=False
	return redirect(reverse('my_users:index'))
# Create your views here.

apps/logreg/templates/logreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login-Registration</title>
</head>
<body>
	<div id="registration">
		{% if messages %}
			{% for message in messages %}
				{{message}}
			{% endfor %}
		{% endif %}
		<h1>Registration</h1>
		<form action="{% url 'my_users:register_user' %}" method = "POST">
		{% csrf_token %}
			<p>First Name: <input type="text" name="first_name"></p>
			<p>Last Name: <input type="text" name="last_name"></p>
			<p>Email: <input type="text" name="email"></p>
			<p>Password: <input type="password" name="password"></p>
			<p>Confirm Password: <input type="password" name="confirm_password"></p>
			<input type="submit" name="Register">
		</form>
	</div> <!-- end of registration  -->
	<div id="Login">
		<h1>Login</h1>
			<form action="{% url 'my_users:login_user' %}" method = "POST">
			{% csrf_token %}
				<p>Email:<input type="text" name="email"></p>
				<p>Password:<input type="password" name="password"></p>
				<input type="submit" name="Login">
			</form>
	</div> <!-- end of login -->
	
</body>
</html>

apps/logreg/templates/logreg/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Success</title>
	<style>
		h3{
			color: green;
		}
	</style>
</head>
<body>
	{% if messages %}
		{% for message in messages %}
		<h3>{{message}}</h3>
		{% endfor %}
	{% endif %}
	<a href="{% url 'my_users:logout' %}">Logout</a>
	<a href="{% url 'my_courses:adduser' %}"><button>View Courses</button></a>
	<h3>View Some Other Projects!</h3>
	<a href="{% url 'my_randomword:index' %}"><button>Random Word Project</button></a>
	<a href="{% url 'my_timedisplay:index' %}"><button>Date Time Display</button></a>
	<a href="{% url 'my_survey:index' %}"><button>Survey</button></a>
</body>
</html>