apps/survey/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^process$', views.process, name="process"),
    url(r'^result$', views.result, name="result"), 
    url(r'^reset$', views.reset, name="reset")
]

multiple_apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
    
    url(r'^', include('apps.logreg.urls', namespace="my_users")),
    url(r'^courses/', include('apps.courses.urls', namespace="my_courses")),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace="my_timedisplay")),
    url(r'^randomword/', include('apps.randomword.urls', namespace="my_randomword")),
    url(r'^survey/', include('apps.survey.urls', namespace="my_survey")),
]

apps/survey/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/survey/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

def index(request):
	return render(request,'survey/index.html')

def process(request):
	count = 0
	if 'count' not in request.session:
		request.session['count']= 0
	request.session['count'] += 1 
	
	request.session["name"] = request.POST["name"]
	request.session["location"] = request.POST["location"]
	request.session["language"] = request.POST["language"]
	request.session["comments"] = request.POST["comments"]
	
	return redirect(reverse('my_survey:result'))

def result(request):
	return render(request, 'survey/result.html')

def reset(request):
	return redirect(reverse('my_survey:index'))

apps/survey/templates/survey/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'survey/css/styles.css' %}" media="screen" title="no title">
</head>
<body>
	<div id="wrapper">
	<form action="{% url 'my_survey:process' %}" method="post">
		{% csrf_token %}
		<div id="leftside">
			<p>Your Name:</p>
			<p>Dojo Location:</p>
			<p>Favorite Language:</p>
			<p>Comment (optional):</p>
			<textarea placeholder="Please comment..." value="text" name="comments" rows="5" cols="50"> </textarea>
			<a href="/"><button>Submit</button></a>
		</div> <!-- end of leftside -->
		<div id="rightside">
				<input type="text" name="name">
				<select name="location">
					<option value="seattle">Seattle</option>
					<option value="chicago">Chicago</option>
					<option value="san_francisco">San Francisco</option>
				</select>
				<select name="language">
					<option value="python">Python</option>
					<option value="javascript">JavaScript</option>
					<option value="ruby">Ruby on Rails</option>
				</select>
			</form>
		</div> <!-- end of rightside -->
		
	</div> <!-- end of wrapper -->
</body>
</html>

apps/survey/templates/survey/result.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Results Page</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'survey/css/styles.css' %}" media="screen" title="no title">
</head>
<body>
	<div id="wrapper">
		<h1>Thanks for submitting this form!</h1>
		<h2> You have submitted this form {{request.session.count}} times now.</h2>
		<div id="leftside">
			<h2>Submitted Information</h2>
			<p>Name:</p>
			<p>Dojo Location:</p>
			<p>Favorite Language:</p>
			<p>Comment:</p>
		</div> <!-- end of leftside -->
		<div id="rightside">
			<p>{{request.session.name}}</p>
			<p>{{request.session.location}}</p>
			<p>{{request.session.language}}</p>
			<p>{{request.session.comments}}</p>
	</div> <!-- end of wrapper -->
	<a href="{% url 'my_survey:reset' %}"><button>Go Back</button></a>
</body>
</html>