apps/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^create_course$', views.create_course, name="create_course"),
    url(r'^(?P<id>\d+)/remove$', views.remove, name="remove"),
    url(r'^addusertocourse$', views.addusertocourse, name="users_courses"),
    url(r'^adduser$', views.adduser, name="adduser")
]

apps/logreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register_user$', views.register_user, name="register_user"),
    url(r'^success$', views.success, name="success"),
    url(r'^login_user$', views.login_user, name="login_user"),
    url(r'^logout$',views.logout, name="logout")
]

multiple_apps/urls.py
from django.conf.urls import url, include


urlpatterns = [
    
    url(r'^', include('apps.logreg.urls', namespace="my_users")),
    url(r'^courses/', include('apps.courses.urls', namespace="my_courses")),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace="my_timedisplay")),
    url(r'^randomword/', include('apps.randomword.urls', namespace="my_randomword")),
    url(r'^survey/', include('apps.survey.urls', namespace="my_survey")),
]

apps/courses/models.py
from __future__ import unicode_literals
from ..logreg.models import User
from django.db import models

class Courses(models.Model):
	name = models.CharField(max_length= 255)
	description = models.TextField(null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	users= models.ManyToManyField(User, related_name="courses")

# Create your models here.

apps/courses/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import Courses
from ..logreg.models import User
from django.db.models import Count

def index(request):
	context = {
		"blah" : Courses.objects.all()
	}
	return render(request,'courses/index.html', context)

def create_course(request):
	
	Courses.objects.create(name=request.POST["name"],description=request.POST["description"]) 
	
	return redirect(reverse('my_courses:index'))

def remove(request,id):

	course_to_remove= Courses.objects.get(id=id)
	print(course_to_remove.name)
	if request.method == "GET":
		context = {
			"courses": course_to_remove
			}
		return render(request, 'courses/destroy.html', context)
	course_to_remove.delete()
	return redirect(reverse('my_courses:index'))		

def addusertocourse(request):
	user= User.objects.get(id=request.POST['user_id'])
	course = Courses.objects.get(id=request.POST['course_id'])
	course.users.add(user)
	return redirect(reverse('my_courses:adduser'))

def adduser(request):
	print request.POST
	
	context={
		"users": User.objects.all(),
		"courses":Courses.objects.annotate(students=Count('users__id'))
	}
	
	return render(request, 'courses/users_courses.html', context)

apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Remove Description</title>
</head>
<body>
	<h3>Are you sure you want to delete the following course?</h3>
	
	
		<p>Name: {{courses.name}}</p>
		<p>Description: {{courses.description}}</p>
		<a href="{% url 'my_courses:index' %}"><button>No</button></a>
    <form action="{% url 'my_courses:remove' id=courses.id %}" method='post'>
      {% csrf_token %}
      <input class='delete' type="submit" value="Yes! I want to delete this."> 
    </form>
	
</body>
</html>

apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Courses Index Page!!</title>
	
</head>
<body>
	<div id="add_course">
		<form action="{% url 'my_courses:create_course' %}" method="post">
		{% csrf_token %}
			<h1>Add a new course:</h1>
			<h2>Name: <input type="text" name="name" placeholder="type name"></h2>
			<h2>Description: <textarea name="description" rows="4" cols="25"></textarea></h2>
			<p><input type="submit" value = "Add Course"></p>
		</form>
	</div> <!-- end of add_course div -->
	<div id="course_table">
		<h1>Courses</h1>
			<form>
				<table>
					<tr>
						<th>Course Name</th>
						<th>Description</th>
						<th>Date Added</th>
						<th>Actions</th>
					</tr>
					{% for item in blah %}
						<tr>
							<td>{{item.name}}</td>
							<td>{{item.description}}</td>
							<td>{{item.created_at}}</td>
							 <td><a href="{% url 'my_courses:remove' id=item.id %}">Remove</a></td>
					{% endfor %}
					</tr>
					
				</table>
			</form>
	</div> <!-- end of course_table -->
</body>
</html>

apps/courses/templates/courses/users_courses.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Awesome Link Between Users and Courses</title>
</head>
<body>
	<h2>Linking Users and Courses</h2>
	<form action="{% url 'my_courses:users_courses' %}" method="POST">
	{% csrf_token %}
		<select name = "user_id">
		{% for user in users %}
		 <option value="{{user.id}}">
		 {{user.first_name}} {{user.last_name}}
		 </option>
		 {% endfor %}
		 </select>	
	
		<select name = "course_id">
		{% for course in courses %}
		<option value="{{course.id}}">
		{{course.name}}
		</option>
		{% endfor %}
		</select>	
	
		<input type="submit" value = "Add User To Course">
	</form>
	<table>
		<tr><th>Course</th>
			<th>Title</th>
			<th>Number of Users</th>
		</tr>
		{% for course in courses%}
		<tr><td>{{course.id}}</td>
			<td>{{course.name}}</td>
			<td>{{course.students}}</td>
		</tr>
		{% endfor %}
		<a href="{% url 'my_users:success' %}"><button>Return Home</button></a>
</body>
</html>